// src/components/TrainingControlPanel.vue
<template>
  <div class="training-panel">
    <div class="panel-header">
      <div>
        <h2>训练控制模块</h2>
        <p>使用前端 `setInterval` 控制逐步训练，每一步调用后端接口并实时刷新图表、loss 曲线和 accuracy。</p>
      </div>
      <el-tag :type="statusTagType" size="large">{{ trainingState.status || 'idle' }}</el-tag>
    </div>

    <el-card shadow="never" class="control-card">
      <el-form label-width="110px" class="control-form">
        <el-form-item label="算法">
          <el-select v-model="form.algorithm" style="width: 220px">
            <el-option label="线性回归" value="linear_regression" />
            <el-option label="SVM" value="svm" />
            <el-option label="KMeans" value="kmeans" />
          </el-select>
        </el-form-item>

        <el-form-item label="最大步数">
          <el-input-number v-model="form.maxSteps" :min="1" :max="500" />
        </el-form-item>

        <el-form-item label="运行间隔(ms)">
          <el-input-number v-model="form.intervalMs" :min="200" :max="5000" :step="100" />
        </el-form-item>

        <el-form-item label="学习率" v-if="form.algorithm !== 'kmeans'">
          <el-input-number v-model="form.learningRate" :min="0.001" :max="1" :step="0.001" :precision="3" />
        </el-form-item>

        <el-form-item label="聚类数" v-else>
          <el-input-number v-model="form.kValue" :min="2" :max="6" />
        </el-form-item>
      </el-form>

      <div class="actions">
        <el-button type="primary" :loading="loading.init" @click="handleInit">初始化</el-button>
        <el-button :disabled="!sessionId || loading.step || isRunning" @click="handleStep">单步执行</el-button>
        <el-button type="success" :disabled="!sessionId || isRunning" @click="startAutoRun">自动训练</el-button>
        <el-button type="warning" :disabled="!sessionId || !isRunning" @click="handlePause">暂停</el-button>
        <el-button :disabled="!sessionId" :loading="loading.status" @click="fetchStatus">刷新状态</el-button>
      </div>

      <el-descriptions :column="4" border class="summary-panel">
        <el-descriptions-item label="Session ID">{{ sessionId || '未初始化' }}</el-descriptions-item>
        <el-descriptions-item label="当前步数">{{ trainingState.currentStep }}</el-descriptions-item>
        <el-descriptions-item label="Loss">{{ formatMetric(trainingState.loss) }}</el-descriptions-item>
        <el-descriptions-item label="Accuracy">{{ formatMetric(trainingState.metrics.accuracy) }}</el-descriptions-item>
      </el-descriptions>
    </el-card>

    <TwoDimensionalVisualizer
      :mode="viewMode"
      :chart-data="trainingState.visualization"
      title="训练过程二维可视化"
      x-name="特征 X"
      y-name="特征 Y"
    />

    <el-row :gutter="20">
      <el-col :xs="24" :lg="12">
        <MetricTrendChart
          title="Loss 曲线"
          subtitle="每次 step 后追加一个 loss 点"
          series-name="Loss"
          color="#F56C6C"
          :data-points="lossHistory"
        />
      </el-col>

      <el-col :xs="24" :lg="12">
        <MetricTrendChart
          title="Accuracy 曲线"
          subtitle="分类显示 accuracy，其他算法显示质量分数"
          series-name="Accuracy"
          color="#67C23A"
          :data-points="accuracyHistory"
        />
      </el-col>
    </el-row>

    <el-card shadow="never" class="payload-card">
      <template #header>
        <div class="payload-header">
          <span>当前训练状态 JSON</span>
          <el-tag size="small" type="info">实时</el-tag>
        </div>
      </template>
      <pre class="payload-preview">{{ statePreview }}</pre>
    </el-card>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { getTrainingStatus, initTraining, pauseTraining, stepTraining } from '../api/training'
import MetricTrendChart from './MetricTrendChart.vue'
import TwoDimensionalVisualizer from './TwoDimensionalVisualizer.vue'

const form = reactive({
  algorithm: 'linear_regression',
  maxSteps: 50,
  intervalMs: 800,
  learningRate: 0.01,
  kValue: 3
})

const sessionId = ref('')
const timerRef = ref(null)
const isRunning = ref(false)
const isStepPending = ref(false)
const loading = reactive({
  init: false,
  step: false,
  status: false
})

const trainingState = reactive({
  sessionId: '',
  algorithm: 'linear_regression',
  status: 'idle',
  currentStep: 0,
  maxSteps: 0,
  progress: 0,
  loss: null,
  metrics: {},
  parameters: {},
  predictions: [],
  visualization: {
    points: [],
    boundary: [],
    centers: []
  },
  updatedAt: null
})

const lossHistory = ref([])
const accuracyHistory = ref([])

const viewMode = computed(() => {
  if (form.algorithm === 'kmeans') {
    return 'clustering'
  }
  if (form.algorithm === 'svm') {
    return 'classification'
  }
  return 'regression'
})

const statePreview = computed(() => JSON.stringify(trainingState, null, 2))
const statusTagType = computed(() => {
  const map = {
    initialized: 'info',
    running: 'success',
    paused: 'warning',
    completed: 'success',
    stopped: 'danger',
    failed: 'danger',
    idle: 'info'
  }
  return map[trainingState.status] || 'info'
})

function formatMetric(value) {
  if (value === null || value === undefined || Number.isNaN(value)) {
    return '-'
  }
  return Number(value).toFixed(4)
}

function buildInitPayload() {
  const payload = {
    algorithm: form.algorithm,
    datasetId: 'frontend_training_dataset',
    featureColumns: ['x1', 'x2'],
    labelColumn: form.algorithm === 'kmeans' ? null : 'label',
    hyperParams: {},
    trainConfig: {
      maxSteps: form.maxSteps
    }
  }

  if (form.algorithm === 'linear_regression') {
    payload.hyperParams = {
      learningRate: form.learningRate,
      epochs: form.maxSteps,
      fitIntercept: true
    }
  } else if (form.algorithm === 'svm') {
    payload.hyperParams = {
      learningRate: form.learningRate,
      kernel: 'linear',
      cValue: 1.0,
      gamma: 0.1
    }
  } else {
    payload.hyperParams = {
      kValue: form.kValue,
      maxIter: form.maxSteps,
      initMethod: 'k-means++'
    }
  }

  return payload
}

function resetHistory() {
  lossHistory.value = []
  accuracyHistory.value = []
}

function appendMetric(historyRef, step, value) {
  if (value === null || value === undefined || Number.isNaN(Number(value))) {
    return
  }

  const numericValue = Number(value)
  const existingIndex = historyRef.value.findIndex((item) => item.step === step)
  if (existingIndex >= 0) {
    historyRef.value.splice(existingIndex, 1, { step, value: numericValue })
  } else {
    historyRef.value.push({ step, value: numericValue })
  }
}

function applyStatus(payload) {
  trainingState.sessionId = payload.sessionId || sessionId.value
  trainingState.algorithm = payload.algorithm || form.algorithm
  trainingState.status = payload.status || trainingState.status
  trainingState.currentStep = payload.currentStep ?? trainingState.currentStep
  trainingState.maxSteps = payload.maxSteps ?? trainingState.maxSteps
  trainingState.progress = payload.progress ?? trainingState.progress
  trainingState.loss = payload.loss ?? trainingState.loss
  trainingState.metrics = payload.metrics || {}
  trainingState.parameters = payload.parameters || {}
  trainingState.predictions = payload.predictions || []
  trainingState.visualization = payload.visualization || {
    points: [],
    boundary: [],
    centers: []
  }
  trainingState.updatedAt = payload.updatedAt || null

  appendMetric(lossHistory, trainingState.currentStep, trainingState.loss)
  appendMetric(accuracyHistory, trainingState.currentStep, trainingState.metrics.accuracy)
}

function clearRunTimer() {
  if (timerRef.value) {
    clearInterval(timerRef.value)
    timerRef.value = null
  }
  isRunning.value = false
}

async function fetchStatus() {
  if (!sessionId.value) {
    return
  }
  loading.status = true
  try {
    const data = await getTrainingStatus(sessionId.value)
    applyStatus(data)
  } catch (error) {
    ElMessage.error(error.message)
  } finally {
    loading.status = false
  }
}

async function handleInit() {
  clearRunTimer()
  loading.init = true
  try {
    resetHistory()
    const data = await initTraining(buildInitPayload())
    sessionId.value = data.sessionId
    trainingState.sessionId = data.sessionId
    trainingState.status = data.status
    trainingState.currentStep = data.currentStep
    trainingState.maxSteps = data.maxSteps
    await fetchStatus()
    ElMessage.success('训练初始化成功')
  } catch (error) {
    ElMessage.error(error.message)
  } finally {
    loading.init = false
  }
}

async function runSingleStep({ silent = false } = {}) {
  if (!sessionId.value || isStepPending.value) {
    return
  }

  isStepPending.value = true
  if (!silent) {
    loading.step = true
  }

  try {
    const data = await stepTraining(sessionId.value, 1)
    applyStatus(data)
    if (!silent) {
      ElMessage.success('单步执行完成')
    }

    if (['completed', 'stopped', 'failed'].includes(trainingState.status)) {
      clearRunTimer()
    }
  } catch (error) {
    clearRunTimer()
    ElMessage.error(error.message)
  } finally {
    isStepPending.value = false
    loading.step = false
  }
}

function handleStep() {
  if (!sessionId.value) {
    ElMessage.warning('请先初始化训练会话')
    return
  }
  runSingleStep()
}

function startAutoRun() {
  if (!sessionId.value) {
    ElMessage.warning('请先初始化训练会话')
    return
  }

  clearRunTimer()
  isRunning.value = true
  trainingState.status = 'running'
  timerRef.value = setInterval(() => {
    if (isStepPending.value) {
      return
    }
    runSingleStep({ silent: true })
  }, form.intervalMs)
}

async function handlePause() {
  if (!sessionId.value) {
    return
  }

  clearRunTimer()
  try {
    const data = await pauseTraining(sessionId.value)
    trainingState.status = data.status
    await fetchStatus()
    ElMessage.success('自动训练已暂停')
  } catch (error) {
    ElMessage.error(error.message)
  }
}

function resetStateForAlgorithm() {
  clearRunTimer()
  sessionId.value = ''
  resetHistory()
  Object.assign(trainingState, {
    sessionId: '',
    algorithm: form.algorithm,
    status: 'idle',
    currentStep: 0,
    maxSteps: 0,
    progress: 0,
    loss: null,
    metrics: {},
    parameters: {},
    predictions: [],
    visualization: {
      points: [],
      boundary: [],
      centers: []
    },
    updatedAt: null
  })
}

watch(
  () => form.algorithm,
  () => {
    resetStateForAlgorithm()
  }
)

onBeforeUnmount(() => {
  clearRunTimer()
})
</script>

<style scoped>
.training-panel {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.panel-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
}

.panel-header h2 {
  margin: 0 0 8px;
  font-size: 24px;
}

.panel-header p {
  margin: 0;
  color: #606266;
}

.control-card {
  display: flex;
  flex-direction: column;
  gap: 16px;
  border-radius: 16px;
}

.control-form {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.summary-panel {
  margin-top: 4px;
}

.payload-card {
  border-radius: 16px;
}

.payload-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.payload-preview {
  margin: 0;
  padding: 16px;
  overflow: auto;
  font-size: 13px;
  line-height: 1.6;
  color: #dcdfe6;
  border-radius: 12px;
  background: #111827;
}

@media (max-width: 960px) {
  .panel-header {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>

// src/app/training-control-panel.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';

import { ExperimentConfig, TrainingStatusResponse, TrainingViewMode, VisualizationData } from './models';
import { TrainingApiService } from './training-api.service';
import { MetricTrendChartComponent } from './metric-trend-chart.component';
import { TwoDimensionalVisualizerComponent } from './two-dimensional-visualizer.component';

@Component({
  selector: 'app-training-control-panel',
  standalone: true,
  imports: [CommonModule, FormsModule, TwoDimensionalVisualizerComponent, MetricTrendChartComponent],
  template: `
    <section class="card">
      <div class="card-header">
        <div>
          <h2>训练控制模块</h2>
          <p>通过 setInterval 按步调用后端 API，实时更新图表、loss 曲线和 accuracy。</p>
        </div>
        <span class="badge" [class.running]="trainingState.status === 'running'">{{ trainingState.status }}</span>
      </div>

      <div class="grid">
        <label class="field">
          <span>最大步数</span>
          <input type="number" [(ngModel)]="maxSteps" min="1" max="500" />
        </label>

        <label class="field">
          <span>运行间隔 (ms)</span>
          <input type="number" [(ngModel)]="intervalMs" min="200" max="5000" step="100" />
        </label>
      </div>

      <div class="actions">
        <button class="primary" (click)="handleInit()" [disabled]="loading.init">初始化</button>
        <button (click)="handleStep()" [disabled]="!sessionId || loading.step || isRunning">单步执行</button>
        <button class="success" (click)="startAutoRun()" [disabled]="!sessionId || isRunning">自动训练</button>
        <button class="warning" (click)="pause()" [disabled]="!sessionId || !isRunning">暂停</button>
        <button (click)="refreshStatus()" [disabled]="!sessionId || loading.status">刷新状态</button>
      </div>

      <div class="summary">
        <div>
          <strong>Session</strong>
          <span>{{ sessionId || '未初始化' }}</span>
        </div>
        <div>
          <strong>当前步数</strong>
          <span>{{ trainingState.currentStep }}</span>
        </div>
        <div>
          <strong>Loss</strong>
          <span>{{ formatMetric(trainingState.loss) }}</span>
        </div>
        <div>
          <strong>Accuracy</strong>
          <span>{{ formatMetric(safeAccuracy) }}</span>
        </div>
      </div>
    </section>

    <app-two-dimensional-visualizer
      [mode]="viewMode"
      [chartData]="trainingState.visualization"
    ></app-two-dimensional-visualizer>

    <div class="metrics-grid">
      <app-metric-trend-chart
        title="Loss 曲线"
        subtitle="每次 step 后追加一个 loss 点"
        seriesName="Loss"
        color="#ef4444"
        [dataPoints]="lossHistory"
      ></app-metric-trend-chart>
      <app-metric-trend-chart
        title="Accuracy 曲线"
        subtitle="分类显示 accuracy，其他算法显示质量分数"
        seriesName="Accuracy"
        color="#10b981"
        [dataPoints]="accuracyHistory"
      ></app-metric-trend-chart>
    </div>

    <section class="card json-card">
      <div class="card-header">
        <h3>训练状态 JSON</h3>
      </div>
      <pre>{{ trainingState | json }}</pre>
    </section>
  `,
  styles: [`
    .card { background: #fff; border-radius: 18px; padding: 24px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); margin-bottom: 20px; }
    .card-header { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; }
    h2 { margin: 0 0 8px; font-size: 24px; }
    h3 { margin: 0; }
    p { margin: 0; color: #64748b; }
    .badge { padding: 6px 12px; border-radius: 999px; background: #f1f5f9; color: #475569; font-size: 12px; font-weight: 700; text-transform: uppercase; }
    .badge.running { background: #dcfce7; color: #15803d; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-top: 16px; }
    .field { display: flex; flex-direction: column; gap: 8px; font-weight: 600; color: #334155; }
    .field input { border: 1px solid #dbe2ea; border-radius: 12px; padding: 10px 12px; }
    .actions { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 16px; }
    button { border: 1px solid #cbd5f5; background: #fff; color: #1f2937; padding: 10px 16px; border-radius: 12px; cursor: pointer; font-weight: 600; }
    button.primary { background: #2563eb; color: #fff; border-color: #2563eb; }
    button.success { background: #10b981; color: #fff; border-color: #10b981; }
    button.warning { background: #f59e0b; color: #fff; border-color: #f59e0b; }
    button:disabled { opacity: 0.6; cursor: not-allowed; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-top: 16px; padding: 12px; border-radius: 14px; background: #f8fafc; }
    .summary strong { display: block; font-size: 12px; color: #64748b; }
    .summary span { font-size: 15px; font-weight: 600; }
    .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; }
    .json-card pre { margin: 0; background: #111827; color: #e2e8f0; padding: 16px; border-radius: 12px; overflow: auto; font-size: 12px; }
  `]
})
export class TrainingControlPanelComponent implements OnDestroy {
  @Input() config: ExperimentConfig | null = null;

  sessionId = '';
  maxSteps = 50;
  intervalMs = 800;
  isRunning = false;
  loading = {
    init: false,
    step: false,
    status: false
  };

  trainingState: TrainingStatusResponse = {
    sessionId: '',
    algorithm: '',
    status: 'idle',
    currentStep: 0,
    maxSteps: 0,
    progress: 0,
    loss: null,
    metrics: {},
    parameters: {},
    predictions: [],
    visualization: { points: [], boundary: [], centers: [] },
    updatedAt: null
  };

  lossHistory: Array<{ step: number; value: number }> = [];
  accuracyHistory: Array<{ step: number; value: number }> = [];

  private timerId: ReturnType<typeof setInterval> | null = null;
  private subscriptions = new Subscription();

  constructor(private readonly trainingApi: TrainingApiService) {}

  get viewMode(): TrainingViewMode {
    if (this.config?.algorithm === 'kmeans') {
      return 'clustering';
    }
    if (this.config?.algorithm === 'svm') {
      return 'classification';
    }
    return 'regression';
  }

  get safeAccuracy(): number | null {
    const accuracy = this.trainingState.metrics?.['accuracy'];
    if (typeof accuracy === 'number') {
      return accuracy;
    }
    return null;
  }

  handleInit(): void {
    if (!this.config) {
      return;
    }

    this.clearTimer();
    this.loading.init = true;
    this.lossHistory = [];
    this.accuracyHistory = [];

    const payload = this.buildInitPayload();
    const sub = this.trainingApi.initTraining(payload).subscribe({
      next: (data) => {
        this.sessionId = data.sessionId;
        this.trainingState.sessionId = data.sessionId;
        this.trainingState.status = data.status;
        this.trainingState.currentStep = data.currentStep;
        this.trainingState.maxSteps = data.maxSteps;
        this.refreshStatus();
      },
      error: () => {
        this.loading.init = false;
      },
      complete: () => {
        this.loading.init = false;
      }
    });
    this.subscriptions.add(sub);
  }

  handleStep(): void {
    if (!this.sessionId || this.isRunning) {
      return;
    }
    this.loading.step = true;
    const sub = this.trainingApi.stepTraining(this.sessionId, 1).subscribe({
      next: (data) => this.applyStatus(data),
      error: () => {
        this.loading.step = false;
        this.clearTimer();
      },
      complete: () => {
        this.loading.step = false;
      }
    });
    this.subscriptions.add(sub);
  }

  startAutoRun(): void {
    if (!this.sessionId || this.isRunning) {
      return;
    }
    this.isRunning = true;
    this.timerId = setInterval(() => {
      if (!this.sessionId || this.loading.step) {
        return;
      }
      this.loading.step = true;
      const sub = this.trainingApi.stepTraining(this.sessionId, 1).subscribe({
        next: (data) => this.applyStatus(data),
        error: () => this.clearTimer(),
        complete: () => {
          this.loading.step = false;
        }
      });
      this.subscriptions.add(sub);
    }, this.intervalMs);
  }

  pause(): void {
    this.clearTimer();
    if (!this.sessionId) {
      return;
    }
    const sub = this.trainingApi.pauseTraining(this.sessionId).subscribe({
      next: (data) => {
        this.trainingState.status = data.status;
        this.refreshStatus();
      }
    });
    this.subscriptions.add(sub);
  }

  refreshStatus(): void {
    if (!this.sessionId) {
      return;
    }
    this.loading.status = true;
    const sub = this.trainingApi.getTrainingStatus(this.sessionId).subscribe({
      next: (data) => this.applyStatus(data),
      error: () => {
        this.loading.status = false;
      },
      complete: () => {
        this.loading.status = false;
      }
    });
    this.subscriptions.add(sub);
  }

  private applyStatus(payload: TrainingStatusResponse): void {
    this.trainingState = {
      ...payload,
      visualization: payload.visualization || { points: [], boundary: [], centers: [] }
    };

    this.appendMetric(this.lossHistory, payload.currentStep, payload.loss ?? 0);
    const accuracyValue = typeof payload.metrics?.['accuracy'] === 'number'
      ? Number(payload.metrics['accuracy'])
      : null;
    if (accuracyValue !== null) {
      this.appendMetric(this.accuracyHistory, payload.currentStep, accuracyValue);
    }

    if (['completed', 'stopped', 'failed'].includes(payload.status)) {
      this.clearTimer();
    }
  }

  private appendMetric(history: Array<{ step: number; value: number }>, step: number, value: number): void {
    const existingIndex = history.findIndex((item) => item.step === step);
    if (existingIndex >= 0) {
      history.splice(existingIndex, 1, { step, value });
    } else {
      history.push({ step, value });
    }
  }

  private buildInitPayload(): Record<string, unknown> {
    const algorithm = this.config?.algorithm ?? 'linear_regression';
    const basePayload = {
      algorithm,
      datasetId: this.config?.dataset ?? 'frontend_dataset',
      featureColumns: ['x1', 'x2'],
      labelColumn: algorithm === 'kmeans' ? null : 'label',
      hyperParams: { ...this.config?.params },
      trainConfig: { maxSteps: this.maxSteps }
    };

    if (algorithm === 'svm' && !('learningRate' in basePayload.hyperParams)) {
      basePayload.hyperParams = { ...basePayload.hyperParams, learningRate: 0.01 };
    }
    if (algorithm === 'linear_regression' && !('learningRate' in basePayload.hyperParams)) {
      basePayload.hyperParams = { ...basePayload.hyperParams, learningRate: 0.01 };
    }
    if (algorithm === 'kmeans' && !('kValue' in basePayload.hyperParams)) {
      basePayload.hyperParams = { ...basePayload.hyperParams, kValue: 3 };
    }

    return basePayload;
  }

  private clearTimer(): void {
    if (this.timerId) {
      clearInterval(this.timerId);
      this.timerId = null;
    }
    this.isRunning = false;
  }

  formatMetric(value: number | null): string {
    if (value === null || value === undefined || Number.isNaN(value)) {
      return '-';
    }
    return Number(value).toFixed(4);
  }

  ngOnDestroy(): void {
    this.clearTimer();
    this.subscriptions.unsubscribe();
  }
}
