// src/app/experiment-config-panel.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { algorithmOptionsByType, datasetOptions, learningTypeOptions } from './experiment-schemas';
import { AlgorithmSchema, ExperimentConfig, LearningType, ParamSchema } from './models';

@Component({
  selector: 'app-experiment-config-panel',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="card">
      <div class="card-header">
        <div>
          <h2>实验配置面板</h2>
          <p>按课程要求使用 Angular 重构，保留实验配置、动态参数和训练联调能力。</p>
        </div>
        <span class="badge">Angular</span>
      </div>

      <div class="grid">
        <label class="field">
          <span>学习类型</span>
          <select [(ngModel)]="learningType" (ngModelChange)="handleLearningTypeChange($event)">
            <option *ngFor="let item of learningTypeOptions" [ngValue]="item.value">{{ item.label }}</option>
          </select>
        </label>

        <label class="field">
          <span>算法</span>
          <select [(ngModel)]="selectedAlgorithmCode" (ngModelChange)="handleAlgorithmChange($event)">
            <option *ngFor="let item of currentAlgorithms" [ngValue]="item.value">{{ item.label }}</option>
          </select>
          <small>{{ currentAlgorithm?.description }}</small>
        </label>

        <label class="field">
          <span>数据集</span>
          <select [(ngModel)]="dataset">
            <option *ngFor="let item of datasetOptions" [ngValue]="item.value">{{ item.label }}</option>
          </select>
        </label>
      </div>

      <div class="param-grid" *ngIf="currentAlgorithm">
        <div class="param-card" *ngFor="let param of currentAlgorithm.params">
          <label>
            <span>{{ param.label }}</span>
            <ng-container [ngSwitch]="param.type">
              <input
                *ngSwitchCase="'number'"
                type="number"
                [min]="param.min ?? null"
                [max]="param.max ?? null"
                [step]="param.step || 1"
                [(ngModel)]="params[param.key]"
              />

              <select *ngSwitchCase="'select'" [(ngModel)]="params[param.key]">
                <option *ngFor="let option of param.options" [ngValue]="option.value">{{ option.label }}</option>
              </select>

              <label *ngSwitchCase="'switch'" class="switch-field">
                <input type="checkbox" [(ngModel)]="params[param.key]" />
                <span>{{ params[param.key] ? '开启' : '关闭' }}</span>
              </label>
            </ng-container>
          </label>
        </div>
      </div>

      <div class="footer">
        <button class="primary" type="button" (click)="emitConfig()">应用配置到训练模块</button>
      </div>
    </section>
  `,
  styles: [`
    .card { background: #fff; border-radius: 18px; padding: 24px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); }
    .card-header { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; margin-bottom: 20px; }
    h2 { margin: 0 0 8px; font-size: 24px; }
    p { margin: 0; color: #64748b; }
    .badge { padding: 6px 12px; border-radius: 999px; background: #ecfeff; color: #0f766e; font-size: 12px; font-weight: 700; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }
    .field, .param-card label { display: flex; flex-direction: column; gap: 8px; font-weight: 600; color: #334155; }
    .field small { font-weight: 400; color: #64748b; }
    select, input[type='number'] { width: 100%; border: 1px solid #dbe2ea; border-radius: 12px; padding: 10px 12px; background: #fff; }
    .param-grid { margin-top: 20px; display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }
    .param-card { padding: 16px; border-radius: 14px; background: #f8fafc; }
    .switch-field { display: flex; gap: 10px; align-items: center; font-weight: 500; }
    .footer { margin-top: 20px; display: flex; justify-content: flex-end; }
    button.primary { border: 0; border-radius: 12px; padding: 12px 18px; background: #2563eb; color: #fff; font-weight: 600; cursor: pointer; }
  `]
})
export class ExperimentConfigPanelComponent {
  @Output() readonly configChange = new EventEmitter<ExperimentConfig>();

  readonly learningTypeOptions = learningTypeOptions;
  readonly datasetOptions = datasetOptions;

  learningType: LearningType = 'supervised';
  selectedAlgorithmCode = algorithmOptionsByType['supervised'][0].value;
  dataset = datasetOptions[0].value;
  params: Record<string, string | number | boolean> = {};

  get currentAlgorithms(): AlgorithmSchema[] {
    return algorithmOptionsByType[this.learningType];
  }

  get currentAlgorithm(): AlgorithmSchema | undefined {
    return this.currentAlgorithms.find((item) => item.value === this.selectedAlgorithmCode);
  }

  constructor() {
    this.resetParams();
    this.emitConfig();
  }

  handleLearningTypeChange(value: LearningType): void {
    this.learningType = value;
    this.selectedAlgorithmCode = algorithmOptionsByType[value][0].value;
    this.resetParams();
    this.emitConfig();
  }

  handleAlgorithmChange(value: string): void {
    this.selectedAlgorithmCode = value as AlgorithmSchema['value'];
    this.resetParams();
    this.emitConfig();
  }

  emitConfig(): void {
    this.configChange.emit({
      learningType: this.learningType,
      algorithm: this.selectedAlgorithmCode,
      dataset: this.dataset,
      params: { ...this.params }
    });
  }

  private resetParams(): void {
    this.params = {};
    for (const param of this.currentAlgorithm?.params ?? []) {
      this.params[param.key] = param.default;
    }
  }
}

// src/components/ExperimentConfigPanel.vue
<template>
  <div class="experiment-panel">
    <div class="hero">
      <div>
        <h1>机器学习实验配置面板</h1>
        <p>支持监督学习、无监督学习、强化学习的统一实验配置。</p>
      </div>
      <el-tag type="success" size="large">Vue3 + Element Plus</el-tag>
    </div>

    <el-row :gutter="20">
      <el-col :xs="24" :lg="12">
        <div class="panel-stack">
          <LearningTypeSelector
            v-model="form.learningType"
            :options="learningTypeOptions"
          />

          <AlgorithmSelector
            v-model="form.algorithm"
            :options="currentAlgorithms"
            :disabled="!form.learningType"
          />

          <DatasetSelector
            v-model="form.dataset"
            :options="datasetOptions"
            :show-upload="isCsvUpload"
            @file-change="handleFileChange"
          />
        </div>
      </el-col>

      <el-col :xs="24" :lg="12">
        <DynamicParamForm
          v-model="form.params"
          :params="currentParams"
        />
      </el-col>
    </el-row>

    <el-card shadow="never" class="config-card preview-card">
      <template #header>
        <div class="card-header">5. 实验配置预览</div>
      </template>

      <el-descriptions :column="2" border>
        <el-descriptions-item label="学习类型">
          {{ learningTypeLabel || '未选择' }}
        </el-descriptions-item>
        <el-descriptions-item label="算法">
          {{ algorithmLabel || '未选择' }}
        </el-descriptions-item>
        <el-descriptions-item label="数据集">
          {{ datasetLabel || '未选择' }}
        </el-descriptions-item>
        <el-descriptions-item label="上传文件">
          {{ form.uploadFileName || '未上传' }}
        </el-descriptions-item>
      </el-descriptions>

      <pre class="json-preview">{{ formattedPayload }}</pre>
    </el-card>
  </div>
</template>

<script setup>
import { computed, reactive, watch } from 'vue'
import AlgorithmSelector from './AlgorithmSelector.vue'
import DatasetSelector from './DatasetSelector.vue'
import DynamicParamForm from './DynamicParamForm.vue'
import LearningTypeSelector from './LearningTypeSelector.vue'
import {
  algorithmOptionsByType,
  datasetOptions,
  learningTypeOptions
} from '../data/experimentSchemas'

const form = reactive({
  learningType: 'supervised',
  algorithm: '',
  dataset: 'iris',
  params: {},
  uploadFileName: ''
})

const currentAlgorithms = computed(() => {
  return algorithmOptionsByType[form.learningType] || []
})

const currentAlgorithmConfig = computed(() => {
  return currentAlgorithms.value.find((item) => item.value === form.algorithm) || null
})

const currentParams = computed(() => {
  return currentAlgorithmConfig.value?.params || []
})

const isCsvUpload = computed(() => form.dataset === 'csv_upload')

const learningTypeLabel = computed(() => {
  return learningTypeOptions.find((item) => item.value === form.learningType)?.label || ''
})

const algorithmLabel = computed(() => {
  return currentAlgorithmConfig.value?.label || ''
})

const datasetLabel = computed(() => {
  return datasetOptions.find((item) => item.value === form.dataset)?.label || ''
})

const buildDefaultParams = (params = []) => {
  return params.reduce((result, item) => {
    result[item.key] = item.default
    return result
  }, {})
}

watch(
  () => form.learningType,
  (value) => {
    const nextAlgorithms = algorithmOptionsByType[value] || []
    form.algorithm = nextAlgorithms[0]?.value || ''
  },
  { immediate: true }
)

watch(
  () => form.algorithm,
  () => {
    form.params = buildDefaultParams(currentParams.value)
  },
  { immediate: true }
)

watch(
  () => form.dataset,
  (value) => {
    if (value !== 'csv_upload') {
      form.uploadFileName = ''
    }
  }
)

const handleFileChange = (file) => {
  form.uploadFileName = file?.name || ''
}

const formattedPayload = computed(() => {
  return JSON.stringify(
    {
      learningType: form.learningType,
      algorithm: form.algorithm,
      dataset: form.dataset,
      uploadFileName: form.uploadFileName || null,
      params: form.params
    },
    null,
    2
  )
})
</script>

<style scoped>
.experiment-panel {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.hero {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 24px;
  color: #fff;
  border-radius: 20px;
  background: linear-gradient(135deg, #409eff, #67c23a);
}

.hero h1 {
  margin: 0 0 8px;
  font-size: 30px;
}

.hero p {
  margin: 0;
  opacity: 0.9;
}

.panel-stack {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.config-card {
  border-radius: 16px;
}

.preview-card {
  margin-top: 4px;
}

.card-header {
  font-size: 16px;
  font-weight: 600;
}

.json-preview {
  margin: 20px 0 0;
  padding: 16px;
  overflow: auto;
  font-size: 13px;
  line-height: 1.6;
  color: #dcdfe6;
  border-radius: 12px;
  background: #1f2937;
}

@media (max-width: 768px) {
  .hero {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
